// Genshin banner-history scraper (separate per game by design).
// Source: Paimon.moe's maintained `src/data/banners.js` — every character
// event wish since 1.0 with start/end + featured 5★/4★ slugs. Slugs use
// underscores (raiden_shogun) which normalize to the gacha display names.
//
// Output:
//   Database/BannerHistory/gi.json   (canonical)
//   Site/pulls-banners-gi.js         (window.NYX_BANNERS.gi, bundled)
//
// Run: node Scraper/banner-history/gi.mjs   (no CI yet, by request)
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '../..');
const SRC = 'https://raw.githubusercontent.com/MadeBaruna/paimon-moe/main/src/data/banners.js';
const FETCH_TIMEOUT_MS = 20_000;

function toMs(s) {
  const m = String(s).match(/^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})$/);
  if (!m) return Date.parse(s) || 0;
  return Date.UTC(+m[1], +m[2] - 1, +m[3], +m[4], +m[5], +m[6]);
}

const res = await fetch(SRC, { signal: AbortSignal.timeout(FETCH_TIMEOUT_MS) });
if (!res.ok) { console.error('Fetch failed:', res.status); process.exit(1); }
const text = await res.text();

const tmp = path.join(os.tmpdir(), 'pm-banners-' + Date.now() + '.mjs');
fs.writeFileSync(tmp, text);
const mod = await import(pathToFileURL(tmp).href);
fs.rmSync(tmp, { force: true });

const chars = (mod.banners && mod.banners.characters) || [];
const out = chars
  .filter((b) => Array.isArray(b.featured) && b.featured.length)
  .map((b) => ({
    type: 'character',
    version: b.version || '',
    name: b.shortName || b.name,
    start: toMs(b.start),
    end: toMs(b.end),
    featured5: b.featured,
    featured4: b.featuredRare || [],
  }))
  .sort((a, b) => a.start - b.start);

const dbDir = path.resolve(root, 'Database/BannerHistory');
fs.mkdirSync(dbDir, { recursive: true });
fs.writeFileSync(path.join(dbDir, 'gi.json'), JSON.stringify(out));

const js = '// GENERATED by Scraper/banner-history/gi.mjs (source: paimon.moe) — do not edit.\n'
  + 'window.NYX_BANNERS = window.NYX_BANNERS || {};\n'
  + 'window.NYX_BANNERS["gi"] = ' + JSON.stringify(out) + ';\n';
fs.writeFileSync(path.resolve(root, 'Site/pulls-banners-gi.js'), js);

console.log('gi banner-history: ' + out.length + ' character banners ('
  + (out[0] ? out[0].version : '?') + ' → ' + (out[out.length - 1] ? out[out.length - 1].version : '?') + ')');
