import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GAMES, monotonicMerge, preserveOfficialWindows, semanticHash, validateDataset } from './core.mjs';
import { scrapeEndfield, scrapeFandomGame } from './sources.mjs';
import { validateActivityFile } from './activities.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const historyDir = path.resolve(root, 'Database/BannerHistory');
const activityDir = path.resolve(root, 'Database/Activities');
const compatibilityFile = path.resolve(root, 'Site/src/features/gacha/pulls-banners-gi.js');

async function readJson(file) { try { return JSON.parse(await fs.readFile(file, 'utf8')); } catch { return null; } }
function firstStart(record) { return Object.values(record.windowsByRegion || {}).map((x) => x.start).filter(Boolean).sort()[0]; }
function lastEnd(record) { return Object.values(record.windowsByRegion || {}).map((x) => x.end || x.start).filter(Boolean).sort().at(-1); }

export function giCompatibility(dataset) {
  const rows = dataset.records.filter((row) => row.bannerType === 'character' && !row.permanent && firstStart(row)).map((row) => ({
    type:'character', version:row.version || '', name:row.name,
    start:Date.parse(firstStart(row)), end:Date.parse(lastEnd(row)),
    featured5:row.featured.filter((x) => x.entityType === 'character' && x.rarity === 5 && x.primary).map((x) => x.name.toLowerCase().replace(/[^a-z0-9]+/g, '_')),
    featured4:row.featured.filter((x) => x.entityType === 'character' && x.rarity === 4).map((x) => x.name.toLowerCase().replace(/[^a-z0-9]+/g, '_')),
  })).sort((a,b) => a.start - b.start || a.name.localeCompare(b.name));
  if (!rows.length || rows.some((row) => !row.featured5.length || !Number.isFinite(row.start) || !Number.isFinite(row.end))) throw new Error('GI compatibility generation failed');
  return '// GENERATED by Scraper/banner-history/index.mjs from canonical GI records - do not edit.\nwindow.NYX_BANNERS = window.NYX_BANNERS || {};\nwindow.NYX_BANNERS["gi"] = ' + JSON.stringify(rows) + ';\n';
}

export function summarize(datasets, generatedAt) {
  return { schemaVersion:1, generatedAt, games:Object.fromEntries(GAMES.map((game) => {
    const rows = datasets[game].records;
    const starts = rows.map(firstStart).filter(Boolean).sort(); const ends = rows.map(lastEnd).filter(Boolean).sort();
    return [game, { count:rows.length, character:rows.filter((x) => x.bannerType === 'character').length, weapon:rows.filter((x) => x.bannerType === 'weapon').length, mixed:rows.filter((x) => x.bannerType === 'mixed').length, permanent:rows.filter((x) => x.permanent).length, confirmed:rows.filter((x) => x.confirmed).length, dateRange:starts.length ? { start:starts[0], end:ends.at(-1) } : null, revisions:[...new Set(rows.map((x) => `${x.source.kind}:${x.source.revision}`))].sort(), officialRevisions:[...new Set(rows.filter((x) => x.officialSource).map((x) => `${x.officialSource.kind}:${x.officialSource.revision}`))].sort(), contentHash:semanticHash(rows) }];
  })) };
}

const journalFile = path.join(historyDir, '.transaction.json');
async function writeJournalAtomic(file, value) {
  const next = `${file}.next`;
  await fs.writeFile(next, JSON.stringify(value, null, 2));
  JSON.parse(await fs.readFile(next, 'utf8'));
  await fs.rename(next, file);
}

export async function recoverTransaction(file = journalFile) {
  const committedMarker = `${file}.committed`;
  const journal = await readJson(file);
  // No journal means no in-flight transaction; still clear any orphaned committed marker so a
  // future transaction's recovery can never mistake a stale marker for its own commit.
  if (!journal?.targets) { await fs.rm(committedMarker, { force:true }); await fs.rm(`${committedMarker}.next`, { force:true }); await fs.rm(`${file}.next`, { force:true }); return; }
  const committed = await fs.access(committedMarker).then(()=>true).catch(()=>false);
  if (!committed) for (const item of journal.targets) {
    if (await fs.access(item.backup).then(()=>true).catch(()=>false)) { await fs.rm(item.target, { force:true }); await fs.rename(item.backup, item.target); }
    else if (!item.existed) await fs.rm(item.target, { force:true });
    await fs.rm(item.next, { force:true });
  }
  for (const item of journal.targets) { await fs.rm(item.next, { force:true }); await fs.rm(item.backup, { force:true }); }
  // Remove the JOURNAL before the committed marker, for the same reason as transactionalReplace's
  // finalize: once backups are gone, a journal-present/marker-absent state would make a re-entered
  // recovery roll back and delete newly created targets. Journal-first leaves at most an orphaned
  // marker, cleared by the no-journal branch above on the next run.
  await fs.rm(file, { force:true }); await fs.rm(`${file}.next`, { force:true });
  await fs.rm(committedMarker, { force:true }); await fs.rm(`${committedMarker}.next`, { force:true });
}

export async function transactionalReplace(outputs, { journalPath=journalFile, onBoundary=()=>{} } = {}) {
  await recoverTransaction(journalPath);
  const staged = [];
  try {
    for (const [target, content] of outputs) {
      await fs.mkdir(path.dirname(target), { recursive:true });
      const next = `${target}.next`; const backup = `${target}.lkg`;
      await fs.writeFile(next, content); if (target.endsWith('.json')) JSON.parse(await fs.readFile(next, 'utf8'));
      staged.push({ target, next, backup, existed:await fs.access(target).then(()=>true).catch(()=>false) });
    }
    await writeJournalAtomic(journalPath, { schemaVersion:1, phase:'prepared', targets:staged });
    await onBoundary('prepared', -1);
    for (let index=0; index<staged.length; index+=1) {
      const item = staged[index];
      await fs.rm(item.backup, { force:true });
      if (item.existed) await fs.rename(item.target, item.backup);
      await fs.rename(item.next, item.target);
      await onBoundary('swap', index);
    }
    await writeJournalAtomic(`${journalPath}.committed`, { schemaVersion:1, committed:true });
    await onBoundary('committed', -1);
    for (let index=0; index<staged.length; index+=1) { await fs.rm(staged[index].backup, { force:true }); await onBoundary('cleanup', index); }
    // Drop the JOURNAL before the committed marker. The journal's presence is what makes recovery
    // choose the rollback branch, and after cleanup the backups are gone, so a rollback here would
    // DELETE newly created targets (existed:false) and leave a mixed generation. Removing the
    // journal first means a crash in this window leaves only an orphaned marker, which the
    // no-journal recovery branch clears while keeping the already-swapped new generation intact.
    await fs.rm(journalPath, { force:true }); await fs.rm(`${journalPath}.next`, { force:true });
    await onBoundary('finalize', 0);
    await fs.rm(`${journalPath}.committed`, { force:true }); await fs.rm(`${journalPath}.committed.next`, { force:true });
  } catch (error) {
    if (!error?.simulatedCrash) await recoverTransaction(journalPath).catch(() => {});
    throw error;
  }
}

export async function run() {
  await recoverTransaction();
  const generatedAt = new Date().toISOString();
  const candidates = {};
  const results = await Promise.all([
    ...['gi','hsr','zzz','wuwa'].map(async (game) => [game, await scrapeFandomGame(game)]),
    (async () => ['ae', await scrapeEndfield()])(),
  ]);
  for (const [game, records] of results) {
    const candidate = validateDataset({ schemaVersion:1, game, generatedAt, records });
    const previous = await readJson(path.join(historyDir, `${game}.json`));
    if (previous?.schemaVersion === 1) preserveOfficialWindows(previous, candidate);
    candidates[game] = previous?.schemaVersion === 1 ? monotonicMerge(previous, candidate) : candidate;
  }
  for (const game of ['gi','hsr','zzz','wuwa']) validateActivityFile(await readJson(path.join(activityDir, `${game}.json`)));
  const summary = summarize(candidates, generatedAt);
  const compatibility = giCompatibility(candidates.gi);
  const outputs = [];
  for (const game of GAMES) {
    const file = path.join(historyDir, `${game}.json`);
    const current = await readJson(file);
    if (!current || semanticHash(current) !== semanticHash(candidates[game])) outputs.push([file, JSON.stringify(candidates[game], null, 2) + '\n']);
  }
  const manifestFile = path.join(historyDir, 'manifest.json');
  const currentManifest = await readJson(manifestFile);
  if (!currentManifest || semanticHash(currentManifest) !== semanticHash(summary)) outputs.push([manifestFile, JSON.stringify(summary, null, 2) + '\n']);
  const currentCompat = await fs.readFile(compatibilityFile, 'utf8').catch(() => '');
  const normalizeEol = (value) => value.replace(/\r\n/g, '\n');
  if (normalizeEol(currentCompat) !== normalizeEol(compatibility)) outputs.push([compatibilityFile, compatibility]);
  await transactionalReplace(outputs);
  console.log(`Banner history: ${GAMES.map((game) => `${game}=${candidates[game].records.length}`).join(' ')}; ${outputs.length} semantic outputs changed`);
  return { datasets:candidates, summary, outputs:outputs.map(([file]) => path.relative(root, file)) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) run().catch((error) => { console.error(error?.stack || error); process.exit(1); });
